import React, { useState, useEffect } from 'react';
import { db } from '../utils/database';
import type { Stall, StallSession } from '../types';

interface StallLoginProps {
  onLoginSuccess: (stall: StallSession) => void;
}

const toSession = (stall: Stall): StallSession => {
  const { ownerPasswordEnc: _omit, ...session } = stall;
  return session;
};

export const StallLogin: React.FC<StallLoginProps> = ({ onLoginSuccess }) => {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [loginError, setLoginError] = useState('');
  const [currentStalls, setCurrentStalls] = useState<Stall[]>([]);

  // Load current stalls for testing links on mount
  useEffect(() => {
    const fetchStalls = async () => {
      const list = await db.getStalls();
      setCurrentStalls(list);
    };
    fetchStalls();
  }, []);

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoginError('');

    if (!username.trim() || !password.trim()) {
      setLoginError('Both username and password are required.');
      return;
    }

    const stall = await db.verifyStallCredentials(username.trim(), password.trim());

    if (stall) {
      const session = toSession(stall);
      db.setActiveStall(session);
      onLoginSuccess(session);
    } else {
      setLoginError('Invalid username or password. Check the sandbox accounts below!');
    }
  };

  const handleQuickLogin = async (uname: string) => {
    const stalls = await db.getStalls();
    const stall = stalls.find(s => s.ownerUsername === uname);
    if (stall) {
      const session = toSession(stall);
      db.setActiveStall(session);
      onLoginSuccess(session);
    }
  };

  return (
    <div style={{ maxWidth: '480px', margin: '4rem auto 2rem', padding: '1.5rem' }}>
      <div className="glass-panel" style={{ padding: '2.5rem', borderRadius: '24px', boxShadow: '0 10px 30px rgba(0,0,0,0.5)' }}>
        <div style={{ textAlign: 'center', marginBottom: '2rem' }}>
          <span style={{ fontSize: '3.5rem', display: 'block', marginBottom: '0.5rem' }}>🏪</span>
          <h2 className="font-display" style={{ fontSize: '2rem', fontWeight: 700, letterSpacing: '-0.025em', color: 'var(--text-primary)' }}>
            Stall Merchant Portal
          </h2>
          <p style={{ color: 'var(--text-secondary)', fontSize: '0.95rem', marginTop: '0.5rem' }}>
            Enter your credentials generated by the Platform Admin to access your shop.
          </p>
        </div>

        <form onSubmit={handleLogin} style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
          <div>
            <label style={{ display: 'block', marginBottom: '0.5rem', fontSize: '0.875rem', fontWeight: 500, color: 'var(--text-secondary)' }}>
              Username
            </label>
            <input
              type="text"
              className="input-field"
              placeholder="e.g. burger_junction"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              style={{ textTransform: 'lowercase' }}
            />
          </div>

          <div>
            <label style={{ display: 'block', marginBottom: '0.5rem', fontSize: '0.875rem', fontWeight: 500, color: 'var(--text-secondary)' }}>
              Password
            </label>
            <input
              type="password"
              className="input-field"
              placeholder="••••••••"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
            />
            {loginError && (
              <p style={{ color: 'var(--accent-red)', fontSize: '0.8rem', marginTop: '0.5rem' }}>
                ⚠️ {loginError}
              </p>
            )}
          </div>

          <button type="submit" className="btn btn-primary" style={{ width: '100%', padding: '0.75rem', marginTop: '0.5rem' }}>
            Login to Merchant Console
          </button>
        </form>

        <div style={{ margin: '2rem 0', display: 'flex', alignItems: 'center', gap: '1rem' }}>
          <div style={{ flex: 1, height: '1px', background: 'var(--border-color)' }}></div>
          <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>Sandbox Quick-Login</span>
          <div style={{ flex: 1, height: '1px', background: 'var(--border-color)' }}></div>
        </div>

        {/* Quick-login by username only — passwords are encrypted and only ever
            decrypted within the Platform Admin portal, not shown here. */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
          <span style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', fontWeight: 600 }}>Active Stalls (Quick Login):</span>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr', gap: '0.5rem' }}>
            {currentStalls.map(s => (
              <button
                key={s.id}
                type="button"
                onClick={() => handleQuickLogin(s.ownerUsername)}
                className="btn btn-secondary"
                style={{
                  display: 'flex',
                  justifyContent: 'space-between',
                  alignItems: 'center',
                  padding: '0.5rem 0.75rem',
                  fontSize: '0.8rem',
                  textAlign: 'left'
                }}
              >
                <span>{s.logoUrl} <strong>{s.name}</strong></span>
                <code style={{ fontSize: '0.75rem', color: 'var(--accent-cyan)' }}>
                  User: {s.ownerUsername}
                </code>
              </button>
            ))}
          </div>
        </div>

        <div style={{ textAlign: 'center', paddingTop: '1.25rem', borderTop: '1px solid var(--border-color)', marginTop: '1.5rem' }}>
          <p style={{ color: 'var(--text-muted)', fontSize: '0.8rem' }}>
            Need a new merchant account? Log into the **Platform Admin Portal** to generate credentials.
          </p>
        </div>
      </div>
    </div>
  );
};
